version: '3.6'

services:
  mysql:
    image: mysql:8.0.13
    environment:
      - MYSQL_ROOT_PASSWORD=passworld
      - MYSQL_DATABASE=storige
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=db4pss
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.1
    depends_on:
      - mysql
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306